### ISSUE TITLE
[Feature request] Logbook support

### ISSUE THREAD

**Issue by Kristinita** [ManufacturaInd/python-zenlog#8]
### 1. Request

It would be nice, if Zenlog will support [**Logbook**](https://github.com/getlogbook/logbook) — popular alternative Python logger.

### 2. Justification

I don't find Python module, that can highlight Logbook output.

### 3. Example

Example file `SashaLogbook.py`, where include Logbook:

```python
import logbook
import sys

logbook.StreamHandler(sys.stdout,
                      level=logbook.DEBUG).push_application()
log = logbook.Logger("Sasha Logbook")

log.debug("Debug message")
log.warning("Warning message")
log.error("Error message")

```

Output for this file:

```shell
D:\SashaPythonista>python SashaLogbook.py
[2018-01-02 07:50:55.652802] DEBUG: Sasha Logbook: Debug message
[2018-01-02 07:50:55.653802] WARNING: Sasha Logbook: Warning message
[2018-01-02 07:50:55.655799] ERROR: Sasha Logbook: Error message
```

It similar as default Python logging.

Thanks.

**Comment by rlafuente** [comment]
I'm sorry, I completely missed this issue when you filed it!

Looking into Logbook, it seems like a great package and it would surely benefit from color output. However, I think you can do that inside Logbook itself (see [here] about changing the format and [here](http://logbook.readthedocs.io/en/stable/api/more.html#colorized-handlers) for colors). 

This because I'm not really sure that zenlog and logbook would play well together, since they're both capturing the default logging and applying their own rules. 

So I think this is not really a feature that Zenlog can help in, but feel free to reopen this issue if you think otherwise.
